# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
variables:
  GCP_REGION: asia-northeast1
  GCP_PROD_REGION: asia-southeast1
  CONTAINER_IMAGE: asia.gcr.io/${GCP_PROJECT}/c88/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}${GROUP_COMMON_LAST_COMMIT}
  MODULE_DIR: ""
  DEPLOY_FILE_NAME: "./Kubernetes/deployment.yaml"
  DEPLOY_QA_FILE_NAME: "./Kubernetes/deployment_qa.yaml"
  ENV_DEV_URL: https://dev-c88-gateway.hyu.tw/
  ENV_STG_URL: https://stg-c88-gateway.hyu.tw/
  ENV_QA_URL: https://qa-c88-gateway.hyu.tw/
  ENV_PRE_URL: https://pre-c88-gateway.hyu.tw/
  ENV_PROD_URL: https://prod-c88-gateway.hyu.tw/

stages:          # List of stages for jobs, and their order of execution
  - package
  - build
  - deploy

maven-package-dev:
  stage: package
  image: maven:3-jdk-11
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository"
  script:
    - mvn clean package deploy -P $CI_COMMIT_BRANCH -s $CI_PROJECT_DIR/ci_settings.xml -Dmaven.test.skip=true
  cache:
    paths: # ignore path com/c88
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/[a-b|d-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/c[a-n]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/comm[a-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/com/[a-b|d-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/com/c[a-z]*
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}${MODULE_DIR}/target/*.jar
  environment:
    name: dev
    url: ${ENV_DEV_URL}
  # when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

maven-package-stg:
  stage: package
  image: maven:3-jdk-11
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository"
  script:
    - mvn clean package deploy -P $CI_COMMIT_BRANCH -s $CI_PROJECT_DIR/ci_settings.xml -Dmaven.test.skip=true
  cache:
    paths: # ignore path com/c88
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/[a-b|d-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/c[a-n]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/comm[a-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/com/[a-b|d-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/com/c[a-z]*
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}${MODULE_DIR}/target/*.jar
  environment:
    name: stg
    url: ${ENV_STG_URL}
  # when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "stage"

maven-package-qa:
  stage: package
  image: maven:3-jdk-11
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository"
  script:
    - mvn clean package deploy -P $CI_COMMIT_BRANCH -s $CI_PROJECT_DIR/ci_settings.xml -Dmaven.test.skip=true
  cache:
    paths: # ignore path com/c88
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/[a-b|d-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/c[a-n]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/comm[a-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/com/[a-b|d-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/com/c[a-z]*
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}${MODULE_DIR}/target/*.jar
  environment:
    name: qa
    url: ${ENV_QA_URL}
  # when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "qa"

maven-package-pre:
  stage: package
  image: maven:3-jdk-11
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository"
  script:
    - mvn clean package deploy -P $CI_COMMIT_BRANCH -s $CI_PROJECT_DIR/ci_settings.xml -Dmaven.test.skip=true
  cache:
    paths: # ignore path com/c88
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/[a-b|d-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/c[a-n]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/comm[a-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/com/[a-b|d-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/com/c[a-z]*
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}${MODULE_DIR}/target/*.jar
  environment:
    name: pre
    url: ${ENV_PRE_URL}
  # when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "pre"

maven-package-prod:
  stage: package
  image: maven:3-jdk-11
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository"
  script:
    - mvn clean package deploy -P $CI_COMMIT_BRANCH -s $CI_PROJECT_DIR/ci_settings.xml -Dmaven.test.skip=true
  cache:
    paths: # ignore path com/c88
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/[a-b|d-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/c[a-n]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/comm[a-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/com/[a-b|d-z]*
      - ${CI_PROJECT_DIR}${MODULE_DIR}/.m2/repository/com/c[a-z]*
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}${MODULE_DIR}/target/*.jar
  environment:
    name: prod
    url: ${ENV_PROD_URL}
  # when: manual
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

include: # build image 及 deploy k8s
  - project: 'c88/sre/deploy'
    ref: master
    file:
      - 'v2/backend/variables.yml'
      - 'v2/backend/kaniko-build.yml'
      - 'v2/backend/gke-deploy.yml'
