
logging:
  level:
    org:
      springframework:
        security: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#hystrix
feign:
  circuitbreaker:
    enabled: true

payment.url: http://localhost:7778/payment