server:
  port: 8080
  servlet:
    context-path: /risk
spring:
  application:
    name: risk
  datasource:
    url: jdbc:mysql://34.84.138.202:3306/c88?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Y7HJv8Pdd86RtQ92hbPbbhET
  redis:
    host: dev-c88-internal.hyu.tw
    port: 6379
    password: 4c55365c-009b-477b-ae47-07f15947c164
    database: 0
  rabbitmq:
    host: c88-rabbitmq.c88
    port: 5672
    username: default_user_-sfMfhOP_-GyXw-2jFe
    password: XoieAxsqH1G2aJP8vr7lW6G4HOD-QHSl
  kafka:
    listener:
      ack-mode: MANUAL
    bootstrap-servers: 10.250.222.1:9092,10.250.222.2:9092,10.250.222.3:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    cloud:
      function:
        definition: betRecordSettled;betRecordSettledFromLastWithdraw;betRecordMonthly;betRecordYesterday
      stream:
        kafka:
          streams:
            binder:
              configuration:
                default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                commit.interval.ms: 1000
              functions:
                betRecordSettled:
                  applicationId: ${spring.application.name}-betRecordSettled
                betRecordMonthly:
                  applicationId: ${spring.application.name}-betRecordMonthly
                betRecordSettledFromLastWithdraw:
                  applicationId: ${spring.application.name}-betRecordSettledFromLastWithdraw
                betRecordYesterday:
                  applicationId: ${spring.application.name}-betRecordYesterday
        bindings:
          betRecordSettled-in-0:
            destination: bet_record
          betRecordMonthly-in-0:
            destination: bet_record
          betRecordSettledFromLastWithdraw-in-0:
            destination: bet_record
          betRecordSettledFromLastWithdraw-in-1:
            destination: withdraw
          betRecordYesterday-in-0:
            destination: bet_record

redisson:
  address: redis://dev-c88-internal.hyu.tw:6379
  password: 4c55365c-009b-477b-ae47-07f15947c164

logging:
  level:
    org:
      springframework:
        security: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#hystrix
feign:
  circuitbreaker:
    enabled: true
