server:
  port: 8088
  servlet:
    context-path: /risk
spring:
  application:
    name: risk
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: 10.250.222.1:9092,10.250.222.2:9092,10.250.222.3:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  cloud:
    function:
      definition: betRecordSettled;betRecordSettledFromLastWithdraw;betRecordMonthly;betRecordYesterday
    stream:
      kafka:
        streams:
          binder:
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              commit.interval.ms: 1000
            functions:
              betRecordSettled:
                applicationId: ${spring.application.name}-betRecordSettled
              betRecordSettledFromLastWithdraw:
                applicationId: ${spring.application.name}-betRecordSettledFromLastWithdraw
              betRecordMonthly:
                applicationId: ${spring.application.name}-betRecordMonthly
              betRecordYesterday:
                applicationId: ${spring.application.name}-betRecordYesterday
      bindings:
        betRecordSettled-in-0:
          destination: bet_record
        betRecordSettledFromLastWithdraw-in-0:
          destination: bet_record
        betRecordMonthly-in-0:
          destination: bet_record
        betRecordSettledFromLastWithdraw-in-1:
          destination: withdraw
        betRecordYesterday-in-0:
          destination: bet_record

hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 3000