server:
  port: 8080
  servlet:
    context-path: /risk
spring:
  application:
    name: risk
  datasource:
    url: jdbc:mysql://c88-mysql:3306/c88?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: c88
    password: su1.%e3:}S2]Gkh,
  redis:
    host: c88-redis
    port: 6379
    password: 956c449b-bd1a-4bfc-8b90-40424b48cef7
    database: 0
  rabbitmq:
    host: c88-rabbitmq
    port: 5672
    username: default_user_Ol0B5e1lRWjOX3kuehT
    password: GK63WRIeFnym9d9dFAcXQ7MW-x1PisvR
  kafka:
    listener:
      ack-mode: MANUAL
    bootstrap-servers: 10.248.222.1:9092,10.248.222.2:9092,10.248.222.3:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    cloud:
      function:
        definition: betRecordSettled;betRecordSettledFromLastWithdraw;betRecordMonthly;betRecordYesterday
      stream:
        kafka:
          streams:
            binder:
              configuration:
                default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                commit.interval.ms: 1000
              functions:
                betRecordSettled:
                  applicationId: ${spring.application.name}-betRecordSettled
                betRecordMonthly:
                  applicationId: ${spring.application.name}-betRecordMonthly
                betRecordSettledFromLastWithdraw:
                  applicationId: ${spring.application.name}-betRecordSettledFromLastWithdraw
                betRecordYesterday:
                  applicationId: ${spring.application.name}-betRecordYesterday
        bindings:
          betRecordSettled-in-0:
            destination: bet_record
          betRecordMonthly-in-0:
            destination: bet_record
          betRecordSettledFromLastWithdraw-in-0:
            destination: bet_record
          betRecordSettledFromLastWithdraw-in-1:
            destination: withdraw
          betRecordYesterday-in-0:
            destination: bet_record

redisson:
  address: redis://c88-redis:6379
  password: 956c449b-bd1a-4bfc-8b90-40424b48cef7

logging:
  level:
    org:
      springframework:
        security: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#hystrix
feign:
  circuitbreaker:
    enabled: true
