apiVersion: v1
kind: Service
metadata:
  name: _CI_PROJECT_NAME_
  namespace: qa-c88
  labels:
    app: _CI_PROJECT_NAME_
spec:
  selector:
    app: _CI_PROJECT_NAME_
  ports:
  - port: 8080
    name: http
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: _CI_PROJECT_NAME_
  namespace: qa-c88
spec:
  # replicas: 2
  selector:
      matchLabels:
        app: _CI_PROJECT_NAME_
  template:
    metadata:
      labels:
        app: _CI_PROJECT_NAME_
    spec:
      containers:
      - name: _CI_PROJECT_NAME_
        image: _CONTAINER_IMAGE_
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 18083
          name: actuator
          protocol: TCP
        resources:
          limits:
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "50m"
            memory: "1Gi"
        env:
        - name: JAVA_OPTS
          value: "-Xmx1G"
        - name: JAVA_ENV
          value: "k8s__CI_ENVIRONMENT_NAME_"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: actuator
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: actuator
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","curl -X POST 'http://localhost:18083/actuator/shutdown'"]
